// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllMembershipsByOrganizationId = `-- name: GetAllMembershipsByOrganizationId :many
SELECT user_id, organization_id, role, joined_at FROM memberships
WHERE organization_id = $1
`

type GetAllMembershipsByOrganizationIdRow struct {
	UserID         string           `json:"user_id"`
	OrganizationID string           `json:"organization_id"`
	Role           MembershipsRole  `json:"role"`
	JoinedAt       pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) GetAllMembershipsByOrganizationId(ctx context.Context, organizationID string) ([]GetAllMembershipsByOrganizationIdRow, error) {
	rows, err := q.db.Query(ctx, getAllMembershipsByOrganizationId, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllMembershipsByOrganizationIdRow{}
	for rows.Next() {
		var i GetAllMembershipsByOrganizationIdRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE memberships
SET role = $3
WHERE user_id = $1 AND organization_id = $2
`

type UpdateMembershipRoleParams struct {
	UserID         string          `json:"user_id"`
	OrganizationID string          `json:"organization_id"`
	Role           MembershipsRole `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.UserID, arg.OrganizationID, arg.Role)
	return err
}
