// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MembershipsRole string

const (
	MembershipsRoleSuperAdmin MembershipsRole = "super_admin"
	MembershipsRoleAdmin      MembershipsRole = "admin"
	MembershipsRoleManager    MembershipsRole = "manager"
	MembershipsRoleMember     MembershipsRole = "member"
)

func (e *MembershipsRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipsRole(s)
	case string:
		*e = MembershipsRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipsRole: %T", src)
	}
	return nil
}

type NullMembershipsRole struct {
	MembershipsRole MembershipsRole `json:"memberships_role"`
	Valid           bool            `json:"valid"` // Valid is true if MembershipsRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipsRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipsRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipsRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipsRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipsRole), nil
}

type OrganizationInviteStatus string

const (
	OrganizationInviteStatusPending  OrganizationInviteStatus = "pending"
	OrganizationInviteStatusAccepted OrganizationInviteStatus = "accepted"
	OrganizationInviteStatusRejected OrganizationInviteStatus = "rejected"
)

func (e *OrganizationInviteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationInviteStatus(s)
	case string:
		*e = OrganizationInviteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationInviteStatus: %T", src)
	}
	return nil
}

type NullOrganizationInviteStatus struct {
	OrganizationInviteStatus OrganizationInviteStatus `json:"organization_invite_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if OrganizationInviteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationInviteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationInviteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationInviteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationInviteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationInviteStatus), nil
}

type Membership struct {
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           MembershipsRole  `json:"role"`
	JoinedAt       pgtype.Timestamp `json:"joined_at"`
}

type Organization struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	OwnerID   string           `json:"owner_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type OrganizationInvite struct {
	ID             string                   `json:"id"`
	OrganizationID string                   `json:"organization_id"`
	UserID         string                   `json:"user_id"`
	InvitedBy      string                   `json:"invited_by"`
	Status         OrganizationInviteStatus `json:"status"`
	CreatedAt      pgtype.Timestamp         `json:"created_at"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
