// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlc

import (
	"context"
)

const changeOwnerOfOrganizationById = `-- name: ChangeOwnerOfOrganizationById :exec
UPDATE organizations
SET owner_id = $1
WHERE id = $2
`

type ChangeOwnerOfOrganizationByIdParams struct {
	OwnerID string `json:"owner_id"`
	ID      string `json:"id"`
}

func (q *Queries) ChangeOwnerOfOrganizationById(ctx context.Context, arg ChangeOwnerOfOrganizationByIdParams) error {
	_, err := q.db.Exec(ctx, changeOwnerOfOrganizationById, arg.OwnerID, arg.ID)
	return err
}

const checkIfUserIsOwner = `-- name: CheckIfUserIsOwner :one
SELECT owner_id FROM organizations
WHERE id = $1
`

func (q *Queries) CheckIfUserIsOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, checkIfUserIsOwner, id)
	var owner_id string
	err := row.Scan(&owner_id)
	return owner_id, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at
`

type CreateOrganizationParams struct {
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.OwnerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrganizationById = `-- name: DeleteOrganizationById :exec
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganizationById(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationById, id)
	return err
}

const getOrganizationById = `-- name: GetOrganizationById :one
SELECT id, name, owner_id, created_at FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationById(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationById, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationsListByUserId = `-- name: GetOrganizationsListByUserId :many
SELECT o.id, o.name, o.owner_id, o.created_at
FROM organizations o
INNER JOIN memberships m ON m.organization_id = o.id
WHERE m.user_id = $1
`

func (q *Queries) GetOrganizationsListByUserId(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getOrganizationsListByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
