// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_invites.sql

package sqlc

import (
	"context"
)

const createOrganizationInvite = `-- name: CreateOrganizationInvite :one
INSERT INTO organization_invites (organization_id, user_id, invited_by)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, invited_by, status, created_at
`

type CreateOrganizationInviteParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
	InvitedBy      string `json:"invited_by"`
}

func (q *Queries) CreateOrganizationInvite(ctx context.Context, arg CreateOrganizationInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, createOrganizationInvite, arg.OrganizationID, arg.UserID, arg.InvitedBy)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationInviteById = `-- name: GetOrganizationInviteById :one
SELECT id, organization_id, user_id, invited_by, status, created_at
FROM organization_invites
WHERE id = $1
`

func (q *Queries) GetOrganizationInviteById(ctx context.Context, id string) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, getOrganizationInviteById, id)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingOrganizationInvite = `-- name: GetPendingOrganizationInvite :one
SELECT id, organization_id, user_id, invited_by, status, created_at
FROM organization_invites
WHERE organization_id = $1 AND user_id = $2 AND status = 'pending'
`

type GetPendingOrganizationInviteParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetPendingOrganizationInvite(ctx context.Context, arg GetPendingOrganizationInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, getPendingOrganizationInvite, arg.OrganizationID, arg.UserID)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrganizationInviteStatus = `-- name: UpdateOrganizationInviteStatus :one
UPDATE organization_invites
SET status = $2
WHERE id = $1 AND status = 'pending'
RETURNING id, organization_id, user_id, invited_by, status, created_at
`

type UpdateOrganizationInviteStatusParams struct {
	ID     string                   `json:"id"`
	Status OrganizationInviteStatus `json:"status"`
}

func (q *Queries) UpdateOrganizationInviteStatus(ctx context.Context, arg UpdateOrganizationInviteStatusParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, updateOrganizationInviteStatus, arg.ID, arg.Status)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
