// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, description, status, created_by, created_at
`

type CreateProjectParams struct {
	OrganizationID string      `json:"organization_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	CreatedBy      string      `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
