// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, status, priority, due_date, assigned_to, created_by)
VALUES (
  $1,
  $2,
  $3,
  COALESCE($4::task_status, 'todo'),
  COALESCE($5::priority, 'low'),
  $6,
  $7,
  $8
)
RETURNING id, project_id, title, description, status, priority, due_date, assigned_to, created_by, created_at
`

type CreateTaskParams struct {
	ProjectID   string         `json:"project_id"`
	Title       string         `json:"title"`
	Description pgtype.Text    `json:"description"`
	Status      NullTaskStatus `json:"status"`
	Priority    NullPriority   `json:"priority"`
	DueDate     pgtype.Date    `json:"due_date"`
	AssignedTo  pgtype.UUID    `json:"assigned_to"`
	CreatedBy   string         `json:"created_by"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.AssignedTo,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE from tasks
where id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :many
SELECT id, project_id, title, description, status, priority, due_date, assigned_to, created_by, created_at FROM tasks
where project_id = $1 AND assigned_to = $2
`

type GetTaskParams struct {
	ProjectID  string      `json:"project_id"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTask, arg.ProjectID, arg.AssignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTask = `-- name: ListProjectTask :many
SELECT id, project_id, title, description, status, priority, due_date, assigned_to, created_by, created_at FROM tasks
where project_id = $1
`

func (q *Queries) ListProjectTask(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listProjectTask, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3, description = $4, status = $5, priority = $6, due_date = $7, assigned_to = $8
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, description, status, priority, due_date, assigned_to, created_by, created_at
`

type UpdateTaskParams struct {
	ID          string      `json:"id"`
	ProjectID   string      `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      TaskStatus  `json:"status"`
	Priority    Priority    `json:"priority"`
	DueDate     pgtype.Date `json:"due_date"`
	AssignedTo  pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.AssignedTo,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
